# Generated by Django 5.2.3 on 2025-06-28 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('department', models.CharField(default='Society of College in Information Technology and Computing', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('payment_type', models.CharField(choices=[('free', 'Free'), ('custom', 'Custom')], max_length=10)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDateBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
    ]
