# Generated by Django 5.2.3 on 2025-06-29 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
