# Generated by Django 5.2.3 on 2025-07-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='year',
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='late_returns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='on_time_returns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='priority_score',
            field=models.IntegerField(default=1),
        ),
    ]
