# Generated by Django 5.2.3 on 2025-07-19 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_item_created_at_alter_item_custom_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='department',
            field=models.CharField(default='Society of College in Information Technology and Computing', max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_no',
            field=models.CharField(default='I000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='payment_type',
            field=models.CharField(choices=[('free', 'Free'), ('custom', 'Custom')], max_length=10),
        ),
    ]
