# Generated by Django 5.2.3 on 2025-07-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reservation_transaction_id_alter_item_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='item',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
