# Generated by Django 5.2.3 on 2025-07-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_item_payment_type_item_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fee',
            field=models.CharField(default='Free', max_length=20),
        ),
    ]
