# Generated by Django 5.2.3 on 2025-07-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_item_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='fee',
            field=models.CharField(default='Free', max_length=20),
        ),
    ]
