# Generated by Django 5.2.3 on 2025-07-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reservation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='payment_type',
            field=models.CharField(choices=[('free', 'Free'), ('custom', 'Custom')], default='free', max_length=20),
        ),
    ]
