# Generated by Django 4.2.23 on 2025-07-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_item_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
