# Generated by Django 4.2.23 on 2025-07-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_expo_push_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdateblock',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='itemdateblock',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='itemdateblock',
            name='reserved_by',
        ),
        migrations.RemoveField(
            model_name='itemdateblock',
            name='start_time',
        ),
    ]
