# Generated by Django 4.2.23 on 2025-07-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_itemdateblock_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='feedback_status',
            field=models.CharField(blank=True, choices=[('on_time', 'On Time'), ('late', 'Late'), ('not_submitted', 'Not Submitted')], max_length=20, null=True),
        ),
    ]
